{
 "title": "Onstream",
 "tags": [
  "Software",
  "Test",
  "Pytest"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Software",
    "query": "show tag values from OnStream with key = \"Software\""
   },
   {
    "name": "Browser",
    "query": "show tag values from OnStream with key = \"Browser\""
   },
   {
    "name": "URL",
    "query": "show tag values from OnStream with key = \"URL\""
   },
   {
    "name": "Test",
    "query": "show tag values from OnStream with key = \"Test\""
   },
   {
    "name": "PyTest",
    "query": "show tag values from OnStream with key = \"Pytest\""
   },
   {
    "name": "Device",
    "query": "show tag values from OnStream with key = \"Device\""
   }
  ]
 },
 "panels": [
  {
   "title": "PyTest Total Test Failed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"duration_sec\") FROM \"test_result\" WHERE (\"status_tag\" = 'failed') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PyTest Total Test Passed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"duration_sec\") FROM \"test_result\" WHERE (\"status_tag\" = 'passed') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Onstream Errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select \"timeout_exception\" from OnStream Where (\"Software\" =~ /^$Software$/) and (\"Browser\" =~ /^$Browser$/) and (\"URL\" =~ /^$URL$/) and (\"Test\" =~ /^$Test$/) and (\"Pytest\" =~ /^$PyTest$/) and (\"Device\" =~ /^$Device$/) and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select \"loading_screen\" from OnStream Where (\"Software\" =~ /^$Software$/) and (\"Browser\" =~ /^$Browser$/) and (\"URL\" =~ /^$URL$/) and (\"Test\" =~ /^$Test$/) and (\"Pytest\" =~ /^$PyTest$/) and (\"Device\" =~ /^$Device$/) and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select \"unable_to_connect\" from OnStream Where (\"Software\" =~ /^$Software$/) and (\"Browser\" =~ /^$Browser$/) and (\"URL\" =~ /^$URL$/) and (\"Test\" =~ /^$Test$/) and (\"Pytest\" =~ /^$PyTest$/) and (\"Device\" =~ /^$Device$/) and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select \"error_404\" from OnStream Where (\"Software\" =~ /^$Software$/) and (\"Browser\" =~ /^$Browser$/) and (\"URL\" =~ /^$URL$/) and (\"Test\" =~ /^$Test$/) and (\"Pytest\" =~ /^$PyTest$/) and (\"Device\" =~ /^$Device$/) and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select \"element_loading\" from OnStream Where (\"Software\" =~ /^$Software$/) and (\"Browser\" =~ /^$Browser$/) and (\"URL\" =~ /^$URL$/) and (\"Test\" =~ /^$Test$/) and (\"Pytest\" =~ /^$PyTest$/) and (\"Device\" =~ /^$Device$/) and $timeFilter  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select \"element_not_found\" from OnStream Where (\"Software\" =~ /^$Software$/) and (\"Browser\" =~ /^$Browser$/) and (\"URL\" =~ /^$URL$/) and (\"Test\" =~ /^$Test$/) and (\"Pytest\" =~ /^$PyTest$/) and (\"Device\" =~ /^$Device$/) and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PyTest Results",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"test\", \"status_tag\", \"project\",  \"run\", \"duration_sec\" FROM \"test_result\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}